### ISSUE TITLE
Metric modulation

### ISSUE THREAD

**Issue by infojunkie** [felixroos/rhythmical#14]
Hello, thanks for creating this very exciting module! I hope to use it to represent rhythms of the different musical traditions of the world :pray: 

I have a feature request: It would be great to support [metric modulation](https://en.wikipedia.org/wiki/Metric_modulation), which is the generalization of applying a swing feel. The use case would be: given a rhythm, apply a transformation that is described by two `rhythmical` structures: the source and the destination. 

For example, for swing, the transformation would look like:
```transform(bolero, [1, 1], [2, 0, 1])```

Hope this makes sense. Thanks for your consideration!

**Comment by felixroos** [comment]
Hey there! Thanks for your interest in this lib. Being able to represent swing is on my list, though I still had no concrete plan how. Your approach seems like a good idea, but I am not sure if I understand it right. 

As I see it, the second param is the input and the third param is the ouput, transforming straight 8ths to swung 8ths in triplet swing. What I don't understand is how the algorithm will know "where the 8ths are". I guess you refer to the bolero rhythm in the readme:

```
const bolero = [
  // bar 1
  [
    [1, [1, 1, 1]], // beat 1
    [1, [1, 1, 1]], // beat 2
    [1, 1] // beat 3
  ],
  // bar 2
  [
    [1, [1, 1, 1]], // beat 1
    [1, [1, 1, 1]], // beat 2
    [[1, 1, 1], [1, 1, 1]] // beat 3
  ]
];
```

From my understanding, transforming ```[1, 1]``` to ```[2, 0, 1]``` in this example would mean to play the first bar half as slow as the second, which is not what we want. The transform function would need some indication of which level of nesting is meant, for example:

```transform(bolero, [1, 1], [2, 0, 1], 6)```

The number 6 stands for the subdivision: the input has 2 bars in 3/4 time so we have 6 quarter notes. For each quarter note, we want to apply the given transformation. But maybe I am missing some piece of the puzzle and this info is not needed.. 

Regarding swing support in general, I would also like to have a way of setting swing to any float value, like 0.6 / 60% swing. Of course 60% swing could also be seen as quintuplet swing ```[1, 1]``` => ```[3, 0, 0, 2, 0]``` but being able to set a float value is better to work with in some cases. 

Of course, being able to apply metric modulation is not just useful to control swing. FYI I already did a rewrite of the core features of rhythmical + added an optional [object notation](https://felixroos.github.io/rhythmical-objects) that allows polyphony and more. I will add those features to this repo when they are ready (could take some time).

**Comment by infojunkie** [comment]
Hi, thanks for your response.

> As I see it, the second param is the input and the third param is the ouput, transforming straight 8ths to swung 8ths in triplet swing.

Yes, that's what I meant.

> The transform function would need some indication of which level of nesting is meant, 

Makes sense :smile: Although I would ask if it's possible to specify a subdivision at the _bar_ level (as opposed to the full rhythm level), to keep the function call agnostic to the length of the input rhythm. So in your example, would specifying 3 (beats per measure) instead of 6 be enough information for the transformation to identfiy the 8th notes in each bar?

**Comment by felixroos** [comment]
> Although I would ask if it's possible to specify a subdivision at the bar level

It would be much more practical, although I think it makes the function a little bit biased because 

- it assumes that the first level of the array always represents measures. In some cases, we might want the first level of the array to represent different sections or something similar. 
- We might have bars with different time signatures

As an alternative, it could work like that:

```js
bolero.map(bar => transform(bar, [1, 1], [2, 0, 1], 3));
```

**Comment by infojunkie** [comment]
Thanks! That API looks great. 

While you were answering, I was wondering if alternatively, specifying the nesting level instead of the subdivisions would afford more genericity: 0 == the level of the bar, 1 == next level, etc.

**Comment by felixroos** [comment]
I am not sure if that would work, because the level of nesting does not control the subdivision, as the same rhythm can be represented with different nestings. For example, we could completely leave out the 8ths notes like this:

```js
const boleroFlatter = [
  // bar 1
  [
    [3, 0, 0, 1, 1, 1], // beat 1
    [3, 0, 0, 1, 1, 1], // beat 2
    [1, 1] // beat 3
  ],
  // bar 2
  [
    [3, 0, 0, 1, 1, 1], // beat 1
    [3. 0, 0, 1, 1, 1], // beat 2
    [1, 1, 1, 1, 1, 1] // beat 3
  ]
];
```

With that nesting, I wonder how the call would look like? Using the previous idea, the call would look the same. So in short, using the level as last param, we need to know the structure of the input rhythm. Using the subdivision as last param, the structure can be unknown. But I might need to think about this a little more to fully understand it.

**Comment by felixroos** [comment]
FYI check out the  [rhythmical editor](https://felixroos.github.io/blog/notes/RhythmicalEditor) I made (totally experimental, only tested on chrome), which uses the newer object notation. The example bolero rhythm looks like this:

```json
{
  "duration": 6,
  "sequential": [
    [
      ["sn", ["sn", "sn", "sn"]],
      ["sn", ["sn", "sn", "sn"]],
      ["sn", "sn"]
    ],
    [
      ["sn", ["sn", "sn", "sn"]],
      ["sn", ["sn", "sn", "sn"]],
      [
        ["sn", "sn", "sn"],
        ["sn", "sn", "sn"]
      ]
    ]
  ]
}
```

Without the 8ths notes, it can be heard like this:

```json
{
  "duration": 6,
  "sequential": [
    [
      [{ "sequential": ["sn"], "duration": 3 }, "sn", "sn", "sn"],
      [{ "sequential": ["sn"], "duration": 3 }, "sn", "sn", "sn"],
      ["sn", "sn"]
    ],
    [
      [{ "sequential": ["sn"], "duration": 3 }, "sn", "sn", "sn"],
      [{ "sequential": ["sn"], "duration": 3 }, "sn", "sn", "sn"],
      ["sn", "sn", "sn", "sn", "sn", "sn"]
    ]
  ]
}
```

The above notation might look a little bit verbose, but I will add the string shorthand for duration soon, which will allow to do this:


```json
{
  "duration": 6,
  "sequential": [
    [
      ["sn*3", "sn", "sn", "sn"],
      ["sn*3", "sn", "sn", "sn"],
      ["sn", "sn"]
    ],
    [
      ["sn*3", "sn", "sn", "sn"],
      ["sn*3", "sn", "sn", "sn"],
      ["sn", "sn", "sn", "sn", "sn", "sn"]
    ]
  ]
}
```

**Comment by felixroos** [comment]
One more FYI, if you're curious about how this stuff works, check out my [in depth post about rhythmical trees](https://felixroos.github.io/rhythmical-trees). Now I'm out for today 🙂

**Comment by infojunkie** [comment]
Thanks for all your replies, I'll have fun digging into it.

**Comment by felixroos** [comment]
I stopped working on this lib, as I moved to developing [strudel](https://github.com/tidalcycles/strudel), which is similar to rhythmical (but much more powerful)
